version: '2'
services:
    sqlserverapplication-app:
        image: sqlserverapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserverapplication-mssql:1433;database=SqlServerApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sqlserverapplication-mssql:
        extends:
            file: mssql.yml
            service: sqlserverapplication-mssql
